insert into bookmodule_book (title, author, price, edition) values ('Ruthless People', 'Hardy Lyngsted', 'Euro', 3);
insert into bookmodule_book (title, author, price, edition) values ('Which Way to the Front?', 'Lari Fisbey', 'Euro', 3);
insert into bookmodule_book (title, author, price, edition) values ('Ice Bound', 'Gabbie Bartholomew', 'Baht', 8);
insert into bookmodule_book (title, author, price, edition) values ('Easy Wheels', 'Marsiella Cordero', 'Dollar', 2);
insert into bookmodule_book (title, author, price, edition) values ('Ping Pong', 'Dre Rowley', 'Yuan Renminbi', 5);
insert into bookmodule_book (title, author, price, edition) values ('Saludos Amigos', 'Christen Meechan', 'Yuan Renminbi', 5);
insert into bookmodule_book (title, author, price, edition) values ('Living with Wolves', 'Harper Clymer', 'Euro', 9);
insert into bookmodule_book (title, author, price, edition) values ('Dead Zone, The', 'Caroline Killeley', 'Hryvnia', 8);
insert into bookmodule_book (title, author, price, edition) values ('Chu Chin Chow', 'Prue Bowater', 'Euro', 3);
insert into bookmodule_book (title, author, price, edition) values ('ThanksKilling 3 ', 'Hodge Ondrus', 'Ruble', 9);
insert into bookmodule_book (title, author, price, edition) values ('Remember Me', 'Corene Huddle', 'Ruble', 8);
insert into bookmodule_book (title, author, price, edition) values ('Hoop Dreams', 'Joachim McCarry', 'Rupiah', 2);
insert into bookmodule_book (title, author, price, edition) values ('Clash by Night', 'Cyndia Gerrans', 'Real', 10);
insert into bookmodule_book (title, author, price, edition) values ('Great K & A Train Robbery, The', 'Wyn Franchyonok', 'Shekel', 7);
insert into bookmodule_book (title, author, price, edition) values ('The Importance of Being Earnest', 'Cari Hazelton', 'Zloty', 1);
insert into bookmodule_book (title, author, price, edition) values ('Star Is Born, A', 'Agnese Cranney', 'Rupiah', 6);
insert into bookmodule_book (title, author, price, edition) values ('Deliverance', 'Jordanna Jorn', 'Rupiah', 3);
insert into bookmodule_book (title, author, price, edition) values ('Niagara Motel', 'Conant Slora', 'Euro', 3);
insert into bookmodule_book (title, author, price, edition) values ('War of the Worlds 2: The Next Wave', 'Judye Ganforth', 'Ruble', 9);
insert into bookmodule_book (title, author, price, edition) values ('Generation, A (Pokolenie)', 'Crissie Broy', 'Yuan Renminbi', 2);
insert into bookmodule_book (title, author, price, edition) values ('Loser', 'Frannie Purse', 'Rupiah', 5);
insert into bookmodule_book (title, author, price, edition) values ('Next Door (Naboer)', 'Bowie Conti', 'Yuan Renminbi', 6);
insert into bookmodule_book (title, author, price, edition) values ('Enchantment', 'Kalle Tingle', 'Sol', 2);
insert into bookmodule_book (title, author, price, edition) values ('Tevye', 'Marla Giraudat', 'Dollar', 1);
insert into bookmodule_book (title, author, price, edition) values ('Murder Ahoy', 'Carmon Longhorne', 'Dinar', 5);
insert into bookmodule_book (title, author, price, edition) values ('Skenbart: En film om tåg', 'Hadley Golledge', 'Sol', 6);
insert into bookmodule_book (title, author, price, edition) values ('Valiant', 'Seka McQuade', 'Yuan Renminbi', 7);
insert into bookmodule_book (title, author, price, edition) values ('Crazy Love', 'Cacilie Loudian', 'Euro', 1);
insert into bookmodule_book (title, author, price, edition) values ('Knightriders', 'Aubrie Manley', 'Balboa', 7);
insert into bookmodule_book (title, author, price, edition) values ('Higher Learning', 'Ki Tash', 'Yuan Renminbi', 8);
insert into bookmodule_book (title, author, price, edition) values ('Fist of Jesus', 'Franz Collen', 'Peso', 8);
insert into bookmodule_book (title, author, price, edition) values ('Hero', 'Winne Guillford', 'Peso', 4);
insert into bookmodule_book (title, author, price, edition) values ('Grand Masti', 'Deirdre Badham', 'Peso', 10);
insert into bookmodule_book (title, author, price, edition) values ('Hawks and Sparrows (Uccellacci e Uccellini)', 'Gauthier Courtois', 'Peso', 7);
insert into bookmodule_book (title, author, price, edition) values ('Maradona by Kusturica', 'Jessica Brownbill', 'Hryvnia', 8);
insert into bookmodule_book (title, author, price, edition) values ('Weird Woman', 'Wilek Dobbins', 'Peso', 8);
insert into bookmodule_book (title, author, price, edition) values ('The Sea Chase', 'Reube Cuming', 'Naira', 6);
insert into bookmodule_book (title, author, price, edition) values ('Winner, The', 'Peri Cordey', 'Hryvnia', 3);
insert into bookmodule_book (title, author, price, edition) values ('Eternity and a Day (Mia aoniotita kai mia mera)', 'Burk Pindar', 'Lek', 5);
insert into bookmodule_book (title, author, price, edition) values ('Uninvited, The', 'Joshuah Kitley', 'Zloty', 4);
insert into bookmodule_book (title, author, price, edition) values ('Tokyo Story (Tôkyô monogatari)', 'Laurena Crossland', 'Yuan Renminbi', 6);
insert into bookmodule_book (title, author, price, edition) values ('Winter Passing', 'Riane Ivantyev', 'Guarani', 5);
insert into bookmodule_book (title, author, price, edition) values ('Addiction, The', 'Petrina Sandaver', 'Krona', 2);
insert into bookmodule_book (title, author, price, edition) values ('Khartoum', 'Alley Harlowe', 'Dollar', 6);
insert into bookmodule_book (title, author, price, edition) values ('Nordkraft', 'Sabina Thormwell', 'Rupiah', 9);
insert into bookmodule_book (title, author, price, edition) values ('Stella Maris', 'Nina Kopelman', 'Kyat', 2);
insert into bookmodule_book (title, author, price, edition) values ('King of Escape, The (Le roi de l''évasion)', 'Gordie Pigott', 'Rupiah', 10);
insert into bookmodule_book (title, author, price, edition) values ('Touch the Sound: A Sound Journey with Evelyn Glennie', 'Christan Newbery', 'Zloty', 8);
insert into bookmodule_book (title, author, price, edition) values ('Racing Dreams', 'Leanora Raysdale', 'Ruble', 2);
insert into bookmodule_book (title, author, price, edition) values ('Two Faces of January, The', 'Wyn Schimaschke', 'Peso', 4);
insert into bookmodule_book (title, author, price, edition) values ('History of the Eagles', 'Wittie Maffini', 'Yen', 2);
insert into bookmodule_book (title, author, price, edition) values ('To Rome with Love', 'Bernardine Seares', 'Peso', 7);
insert into bookmodule_book (title, author, price, edition) values ('Life''s a Breeze', 'Lothario Wedge', 'Euro', 6);
insert into bookmodule_book (title, author, price, edition) values ('911 in Plane Site', 'Crin Burchett', 'Dram', 3);
insert into bookmodule_book (title, author, price, edition) values ('Broken Vessels', 'Wendeline Le Quesne', 'Yuan Renminbi', 2);
insert into bookmodule_book (title, author, price, edition) values ('Rashomon (Rashômon)', 'Jack Sexten', 'Sol', 8);
insert into bookmodule_book (title, author, price, edition) values ('Age of Innocence, The', 'Jojo Figurski', 'Rupiah', 10);
insert into bookmodule_book (title, author, price, edition) values ('World Trade Center', 'Artemis Cabel', 'Yuan Renminbi', 8);
insert into bookmodule_book (title, author, price, edition) values ('MirrorMask', 'Gladi Chaudron', 'Boliviano', 2);
insert into bookmodule_book (title, author, price, edition) values ('First Strike', 'Georgie Chasles', 'Ruble', 1);
insert into bookmodule_book (title, author, price, edition) values ('Onionhead', 'Jacintha Baldi', 'Rupiah', 3);
insert into bookmodule_book (title, author, price, edition) values ('Seopyeonje', 'Herc Mapples', 'Peso', 7);
insert into bookmodule_book (title, author, price, edition) values ('Blue Crush', 'Ardis Paulton', 'Dong', 3);
insert into bookmodule_book (title, author, price, edition) values ('Without Lying Down: Frances Marion and the Power of Women in Hollywood', 'Fifi Drioli', 'Yuan Renminbi', 7);
insert into bookmodule_book (title, author, price, edition) values ('Stunt Rock', 'Renato Hubach', 'Rupiah', 1);
insert into bookmodule_book (title, author, price, edition) values ('The Remaining', 'Avie Kira', 'Yuan Renminbi', 3);
insert into bookmodule_book (title, author, price, edition) values ('Angriest Man in Brooklyn, The', 'Melony Veighey', 'Euro', 9);
insert into bookmodule_book (title, author, price, edition) values ('Hansel & Gretel Get Baked', 'Pacorro Oganesian', 'Dollar', 3);
insert into bookmodule_book (title, author, price, edition) values ('Martin', 'Vivie Prandini', 'Rupiah', 4);
insert into bookmodule_book (title, author, price, edition) values ('Inland Empire', 'Tobiah Bakhrushkin', 'Real', 1);
insert into bookmodule_book (title, author, price, edition) values ('Maybe, Maybe Not (Bewegte Mann, Der)', 'Kerr Langhor', 'Euro', 5);
insert into bookmodule_book (title, author, price, edition) values ('Harry and Tonto', 'Sibby Leggott', 'Yuan Renminbi', 9);
insert into bookmodule_book (title, author, price, edition) values ('Divine Secrets of the Ya-Ya Sisterhood', 'Nicolea Manoelli', 'Dollar', 8);
insert into bookmodule_book (title, author, price, edition) values ('Outside Ozona', 'Fredek Burmaster', 'Dollar', 2);
insert into bookmodule_book (title, author, price, edition) values ('Among Us (Onder Ons)', 'Ysabel Reily', 'Dollar', 1);
insert into bookmodule_book (title, author, price, edition) values ('Up in the Air', 'Cinnamon Andreazzi', 'Rupiah', 1);
insert into bookmodule_book (title, author, price, edition) values ('Hunt, The (Caza, La)', 'Viola Mylechreest', 'Yuan Renminbi', 4);
insert into bookmodule_book (title, author, price, edition) values ('Bound by Honor (a.k.a. Blood In, Blood Out)', 'Pembroke De Maine', 'Euro', 10);
insert into bookmodule_book (title, author, price, edition) values ('Subject Was Roses, The', 'Sapphire Bleythin', 'Dollar', 10);
insert into bookmodule_book (title, author, price, edition) values ('Vizontele Tuuba', 'Chester Hickin', 'Yuan Renminbi', 7);
insert into bookmodule_book (title, author, price, edition) values ('Comedian', 'Hatty Eggar', 'Marka', 7);
insert into bookmodule_book (title, author, price, edition) values ('Streetcar Named Desire, A', 'Rodge Shelsher', 'Ariary', 9);
insert into bookmodule_book (title, author, price, edition) values ('Gus', 'Arlen Demare', 'Yuan Renminbi', 10);
insert into bookmodule_book (title, author, price, edition) values ('Song of Bernadette, The', 'Godwin Yesichev', 'Rupiah', 2);
insert into bookmodule_book (title, author, price, edition) values ('Tokyo Joe', 'Petronia Luquet', 'Euro', 5);
insert into bookmodule_book (title, author, price, edition) values ('Mister 880', 'Ferdinand Lewry', 'Lev', 1);
insert into bookmodule_book (title, author, price, edition) values ('Blablablá', 'Evangeline Meadmore', 'Cordoba', 4);
insert into bookmodule_book (title, author, price, edition) values ('Marnie', 'Tamera Grandisson', 'Peso', 2);
insert into bookmodule_book (title, author, price, edition) values ('Great Diamond Robbery, The', 'Carita Featherbie', 'Peso', 10);
insert into bookmodule_book (title, author, price, edition) values ('Hoot', 'Happy Tetla', 'Peso', 2);
insert into bookmodule_book (title, author, price, edition) values ('Detroit 9000', 'Seth Beckingham', 'Rupiah', 3);
insert into bookmodule_book (title, author, price, edition) values ('All the President''s Men', 'Morie Gatty', 'Rupiah', 7);
insert into bookmodule_book (title, author, price, edition) values ('RoboCop 2', 'Hamlen Spackman', 'Yuan Renminbi', 9);
insert into bookmodule_book (title, author, price, edition) values ('Decline of Western Civilization, The', 'Lianna Benedtti', 'Yuan Renminbi', 4);
insert into bookmodule_book (title, author, price, edition) values ('Seven Brides for Seven Brothers', 'Dallis Sambell', 'Dinar', 6);
insert into bookmodule_book (title, author, price, edition) values ('Twelve Chairs, The', 'Elia Merdew', 'Zloty', 4);
insert into bookmodule_book (title, author, price, edition) values ('It''s in the Water', 'Regan Woolham', 'Yen', 5);
insert into bookmodule_book (title, author, price, edition) values ('Dungeonmaster, The', 'Melina Caulfield', 'Yuan Renminbi', 2);
insert into bookmodule_book (title, author, price, edition) values ('Mod Squad, The', 'Bella Haney`', 'Yen', 3);
insert into bookmodule_book (title, author, price, edition) values ('Kino-Eye (Kinoglaz)', 'Dedie Cockell', 'Krona', 2);
